"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var Admin_1 = require("../controllers/Admin");
var auth_1 = require("../middleware/auth");
var router = express_1.default.Router();
router.post("/create", Admin_1.createGame);
router.patch("/changemode/:id", auth_1.verifyToken, Admin_1.changeGameMode);
router.patch("/pause/:id", auth_1.verifyToken, Admin_1.pauseGame);
router.patch("/resume/:id", auth_1.verifyToken, Admin_1.resumeGame);
router.patch("/kickplayer/:id", auth_1.verifyToken, Admin_1.kickPlayer);
router.patch("/restartwithnewpk/:id", auth_1.verifyToken, Admin_1.restartWithNewPk);
router.patch("/varyhiddenprivatekey/:id", auth_1.verifyToken, Admin_1.varyHiddenPrivatekey);
exports.default = router;
